name: CI проверка тестов
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pipx install uv

      - name: Sync dev-deps & run pytest
        run: |
          uv pip sync -d          # ставит dev-группу из pyproject/uv.lock
          uv run pytest -v